### PR TITLE
fix: MessageWebviewClient throw an IllegalStateException [RLM_ERR_INVALIDATED_OBJECT]

### LINKED ISSUE #1752: IllegalStateException: [RLM_ERR_INVALIDATED_OBJECT]: Accessing object of type Message which has been invalidated or deleted
Sentry Issue: [MAIL-ANDROID-3SZ](https://sentry-mobile.infomaniak.com/organizations/sentry/issues/19115/?referrer=github_integration)

```
IllegalStateException: [RLM_ERR_INVALIDATED_OBJECT]: Accessing object of type Message which has been invalidated or deleted
    at com.infomaniak.mail.data.models.message.Message.getUid(Message.kt:322)
    at com.infomaniak.mail.ui.main.thread.ThreadAdapter$bindBody$1$4.invoke(ThreadAdapter.kt:484)
    at com.infomaniak.mail.ui.main.thread.ThreadAdapter$bindBody$1$4.invoke(ThreadAdapter.kt:481)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.onPageFinished(MessageWebViewClient.kt:105)
...
(12 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sirambd**
Fixes MAIL-ANDROID-3SZ
Fix #1752

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt [hunk 1]
```diff
@@ -100,9 +100,10 @@ class MessageWebViewClient(
     }
 
     override fun onPageFinished(webView: WebView, url: String?) {
-        webView.loadUrl("javascript:removeAllProperties(); normalizeMessageWidth(${webView.width.toDp()}, '$messageUid')")
-        super.onPageFinished(webView, url)
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt:104]: Why did you remove this `super` call ?

**Review by KevinBoulongne — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt (hunk 1 above)
Comment (sirambd) [reply app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt:104]: This super is useless

**Review by KevinBoulongne — APPROVED** [review]
