### PR TITLE
Fix create folder

### LINKED ISSUE #1097: IllegalStateException: Unmanaged objects don't support backlinks.
Sentry Issue: [KMAIL-ANDROID-E9](https://sentry-mobile.infomaniak.com/organizations/sentry/issues/3602/?referrer=github_integration)

```
IllegalStateException: Unmanaged objects don't support backlinks.
    at com.infomaniak.mail.data.models.Folder.get_parents(Folder.kt:83)
    at com.infomaniak.mail.data.models.Folder.getParent(Folder.kt:84)
    at com.infomaniak.mail.ui.main.menu.MenuFoldersFragment.checkForFolderCreationErrors(MenuFoldersFragment.kt:63)
    at com.infomaniak.mail.ui.main.menu.MenuDrawerFragment$initNewFolderDialog$1.invoke(MenuDrawerFragment.kt:272)
    at com.infomaniak.mail.ui.main.menu.MenuDrawerFragment$initNewFolderDialog$1.invoke(MenuDrawerFragment.kt:268)
...
(22 additional frame(s) were not displayed)
```

### LINKED ISSUE #1098: IllegalStateException: Unmanaged objects don't support backlinks.
Sentry Issue: [KMAIL-ANDROID-EE](https://sentry-mobile.infomaniak.com/organizations/sentry/issues/3665/?referrer=github_integration)

```
IllegalStateException: Unmanaged objects don't support backlinks.
    at com.infomaniak.mail.data.models.Folder.get_parents(Folder.kt:83)
    at com.infomaniak.mail.data.models.Folder.getParent(Folder.kt:84)
    at com.infomaniak.mail.ui.main.menu.MenuFoldersFragment.checkForFolderCreationErrors(MenuFoldersFragment.kt:63)
    at com.infomaniak.mail.ui.main.menu.MoveFragment$initNewFolderDialog$1$1.invoke(MoveFragment.kt:98)
    at com.infomaniak.mail.ui.main.menu.MoveFragment$initNewFolderDialog$1$1.invoke(MoveFragment.kt:94)
...
(24 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sirambd**
**Description**
When we create a folder, we receive an exception, so we check each character that is blocking and not optimal.

**Enhancement**
Instead of creating a list for each character and going through the list to check whether the folder name is valid or not, we'll let Realm take care of the folder search so we don't have to do all that, and the search is performed asynchronously. (*Change already made on iOS*)

**Fixes**
Fixes #1098, fixes #1097

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/utils/Extensions.kt [hunk 1]
```diff
@@ -366,19 +368,30 @@ fun Fragment.createInputDialog(
...
     fun AlertDialog.setupOnShowListener() = apply {
         setOnShowListener {
             showKeyboard()
             getButton(AlertDialog.BUTTON_POSITIVE).apply {
                 isEnabled = false
                 textInput.doAfterTextChanged {
-                    val error = if (it.isNullOrBlank()) null else onErrorCheck(it.trim())
-                    isEnabled = it?.isNotBlank() == true && error == null
-                    textInputLayout.error = error
+                    if (it.isNullOrBlank()) isEnabled = false else checkValidation(it.trim())
```
Comment (FabianDevel) [inline app/src/main/java/com/infomaniak/mail/utils/Extensions.kt:394]: The layout error is not hidden anymore if the field is empty in one change, nor when the popup is dismissed

**Review by FabianDevel — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/infomaniak/mail/utils/Extensions.kt (hunk 1 above)
Comment (sirambd) [reply app/src/main/java/com/infomaniak/mail/utils/Extensions.kt]: Done ☑

**Review by FabianDevel — APPROVED** [review]
