### PR TITLE
Fix `currentMailbox` not selected

### LINKED ISSUE #916: NullPointerException
Sentry Issue: [KMAIL-ANDROID-19](https://sentry-mobile.infomaniak.com/organizations/sentry/issues/55/?referrer=github_integration)

```
NullPointerException: None
    at com.infomaniak.mail.ui.MainViewModel$forceRefreshMailboxesAndFolders$1.invokeSuspend(MainViewModel.kt:235)
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by FabianDevel**
Depends on #915 

closes #916 
Fixes kmail-android-55

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt [hunk 1]
```diff
@@ -55,8 +56,17 @@ class LaunchActivity : AppCompatActivity() {
             withContext(Dispatchers.Main) {
                 when {
                     user == null -> loginUser()
-                    navigationArgs?.shouldLock != false && isKeyguardSecure() && localSettings.isAppLocked -> startAppLockActivity()
-                    else -> startApp()
+                    navigationArgs?.shouldLock != false && isKeyguardSecure() && localSettings.isAppLocked -> {
+                        startAppLockActivity()
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt:60]: Won't this bug if `getMailboxesCount() == 0L` ?
Same in kDrive ?

**Review by KevinBoulongne — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt (hunk 1 above)
Comment (FabianDevel) [reply app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt]: done 
(kDrive : https://github.com/Infomaniak/android-kDrive/pull/1006)

**Review by KevinBoulongne — APPROVED** [review]

**Review by JorisBodin — APPROVED** [review]
