### PR TITLE
Fix inline not loaded first time and similar Sentry issues

### LINKED ISSUE #837: RuntimeException: java.lang.reflect.InvocationTargetException
Sentry Issue: [KMAIL-ANDROID-5J](https://sentry.infomaniak.com/organizations/infomaniak/issues/113204/?referrer=github_integration)

```
ErrnoException: open failed: ENOENT (No such file or directory)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.shouldInterceptRequest(MessageWebViewClient.kt:51)
...
(5 additional frame(s) were not displayed)

FileNotFoundException: /data/user/0/com.infomaniak.mail/cache/attachments_cache/799767/1645052/unknown: open failed: ENOENT (No such file or directory)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.shouldInterceptRequest(MessageWebViewClient.kt:51)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### LINKED ISSUE #838: RuntimeException: java.lang.reflect.InvocationTargetException
Sentry Issue: [KMAIL-ANDROID-73](https://sentry.infomaniak.com/organizations/infomaniak/issues/115765/?referrer=github_integration)

```
SocketTimeoutException: timeout
    at com.infomaniak.mail.utils.LocalStorageUtils.saveAttachmentToCache(LocalStorageUtils.kt:72)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.shouldInterceptRequest(MessageWebViewClient.kt:47)
...
(18 additional frame(s) were not displayed)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)

RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

### LINKED ISSUE #839: RuntimeException: java.lang.reflect.InvocationTargetException
Sentry Issue: [KMAIL-ANDROID-5Q](https://sentry.infomaniak.com/organizations/infomaniak/issues/113770/?referrer=github_integration)

```
ErrnoException: open failed: EISDIR (Is a directory)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveCacheAttachment(LocalStorageUtils.kt:79)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveAttachmentToCache$saveAttachmentTo(LocalStorageUtils.kt:65)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveAttachmentToCache(LocalStorageUtils.kt:72)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.shouldInterceptRequest(MessageWebViewClient.kt:47)
...
(9 additional frame(s) were not displayed)

FileNotFoundException: /data/user/0/com.infomaniak.mail/cache/attachments_cache/5462/1135875: open failed: EISDIR (Is a directory)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveCacheAttachment(LocalStorageUtils.kt:79)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveAttachmentToCache$saveAttachmentTo(LocalStorageUtils.kt:65)
    at com.infomaniak.mail.utils.LocalStorageUtils.saveAttachmentToCache(LocalStorageUtils.kt:72)
    at com.infomaniak.mail.ui.main.thread.MessageWebViewClient.shouldInterceptRequest(MessageWebViewClient.kt:47)
...
(4 additional frame(s) were not displayed)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### PR DESCRIPTION
**Pull request by sirambd**
- [Fix: Inline not loaded in first load](https://github.com/Infomaniak/android-kMail/commit/ca21b93eb44937ae043412e996f161739cc58f3b)
- Fixes #837
- Fixes #838
- Fixes #839

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt [hunk 1]
```diff
@@ -66,16 +63,14 @@ object LocalStorageUtils {
...
+        return ApiRepository.downloadAttachment(resource).saveAttachmentTo(resource, cacheFile)
     }
 
-    private fun saveCacheAttachment(resource: String, inputStream: InputStream, outputFile: File) = with(outputFile) {
+    fun saveCacheAttachment(resource: String, inputStream: InputStream, outputFile: File) = with(outputFile) {
         if (exists()) delete()
         inputStream.buffered().use {
             parentFile?.mkdirs()
-            outputStream().use { output -> inputStream.copyTo(output) }
+            if (outputFile.createNewFile()) outputStream().use { output -> inputStream.copyTo(output) }
```
Comment (KevinBoulongne) [inline app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt:73]:
```suggestion
            if (outputFile.createNewFile()) outputStream().use(inputStream::copyTo)
```

**Review by KevinBoulongne — CHANGES_REQUESTED** [review]

**Review by KevinBoulongne — APPROVED** [review]
