### PR TITLE
fix: Only retry api calls for the current user 

### LINKED ISSUE #1871: NullPointerException
Sentry Issue: [MAIL-ANDROID-160](https://sentry-mobile.infomaniak.com/organizations/sentry/issues/6847/?referrer=github_integration)

```
NullPointerException: None
    at com.infomaniak.mail.MainApplication$tokenInterceptorListener$1.getApiToken(MainApplication.kt:246)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sirambd**
Fixes MAIL-ANDROID-160
Fix #1871

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt [hunk 1]
```diff
@@ -56,6 +56,8 @@ class LogoutUser @Inject constructor(
         localSettings.removeRegisteredFirebaseUser(userId = user.id)
 
         if (user.id == AccountUtils.currentUserId) {
+            AccountUtils.currentUser = null // Prevent that the user current no longer exists
```
Comment (LunarX) [inline app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt:59]: I'm not sure what you meant with this comment. Maybe you meant `Prevent that the current user no longer exists` but still, if you meant that sentence, the user is set to `null` which means the user is no longer. So what is the actual meaning of this comment?

File: app/src/main/java/com/infomaniak/mail/MainApplication.kt [hunk 2]
```diff
@@ -266,6 +264,8 @@ open class MainApplication : Application(), ImageLoaderFactory, DefaultLifecycle
         }
 
         override suspend fun getApiToken(): ApiToken? = AccountUtils.currentUser?.apiToken
+
+        override fun getCurrentUserId(): Int = AccountUtils.currentUserId
```
Comment (LunarX) [inline app/src/main/java/com/infomaniak/mail/MainApplication.kt:268]: This won't work, the value is computed only once when the tokenInterceptorListener is instanciated

**Review by LunarX — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt (hunk 1 above)
Comment (LunarX) [reply app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt:59]:
```suggestion
            AccountUtils.currentUser = null // Inform that there is no more current user
```

File: app/src/main/java/com/infomaniak/mail/MainApplication.kt (hunk 2 above)
Comment (LunarX) [reply app/src/main/java/com/infomaniak/mail/MainApplication.kt:268]: Actually not

**Review by LunarX — APPROVED** [review]
